//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EasyGen.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDD_PROGRESS                 102
#define CG_IDS_PROGRESS_CAPTION         103
#define IDS_PROGRESS_Q3AMAP             104
#define IDS_ININOTFOUND                 105
#define IDR_MAINFRAME                   128
#define IDR_EASYGETYPE                  129
#define IDD_CMD                         130
#define IDD_EXPORT_Q3A_SETUP            131
#define IDD_BITMAP_IMPORT               134
#define IDD_PREFERENCES                 137
#define IDD_GRIDMANAGER                 139
#define IDD_TAB1                        140
#define IDD_TAB2                        141
#define IDD_TAB3                        142
#define IDB_MOD_HILL                    150
#define IDB_NEMO                        155
#define IDD_FLIPS                       156
#define IDB_FLIPH                       162
#define IDB_FLIPB                       163
#define IDB_FLIPC                       164
#define IDB_FLIPD                       165
#define IDB_FLIPE                       166
#define IDB_FLIPF                       167
#define IDB_FLIPG                       168
#define IDB_FLIPA                       169
#define IDD_TAB4                        172
#define IDD_IMPORT_FROMMAP              173
#define IDB_AXES                        174
#define IDI_STEP_UP                     176
#define IDI_STEP_DOWN                   177
#define IDI_STEP_RIGHT                  178
#define IDI_STEP_LEFT                   179
#define IDI_STEP_BACKWARD               180
#define IDI_STEP_FORWARD                181
#define IDB_WARNING                     182
#define IDB_WORLDWARNING                189
#define IDB_WORLDWARNING2               190
#define IDD_Q3MAP2OPTIONS               191
#define IDD_SHADERTEMPLATE              192
#define IDC_CMDLIST                     1000
#define IDC_APPVERSION                  1001
#define IDC_APPAUTHOR                   1002
#define IDC_APPEMAIL                    1003
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_APPSITE                     1004
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_MODIFIERS                   1005
#define IDC_SLSMOOTH                    1006
#define IDC_SLNOISE                     1007
#define IDC_GNOISE                      1008
#define IDC_GSMOOTH                     1009
#define IDC_MODE_ADD                    1010
#define IDC_MODE_MAX                    1011
#define IDC_MODE_IDENT                  1012
#define IDC_MODAPPLY                    1013
#define IDC_GSCALE                      1014
#define IDC_SLSCALE                     1015
#define IDC_X                           1018
#define IDC_Y                           1019
#define IDC_H                           1020
#define IDC_TEXTOP                      1021
#define IDC_TEXNOTTOP                   1022
#define IDC_BOXIT                       1024
#define IDC_DONT_SPECIFY                1027
#define IDC_SPECIFY                     1028
#define IDC_GRIDHEIGHT                  1029
#define IDC_BITMAPEXPPATH               1034
#define IDC_BROWSE_BITMAPEXPPATH        1035
#define IDC_BITMAPIMPPATH               1036
#define IDC_BROWSE_BITMAPIMPPATH        1037
#define IDC_BGCOLORCTRL                 1038
#define IDC_GAMEPATH                    1039
#define IDC_BROWSE_GAMEPATH             1040
#define IDC_PGX                         1041
#define IDC_PGY                         1042
#define IDC_CELLS                       1042
#define IDC_PGZ                         1043
#define IDC_WIDTH                       1043
#define IDC_TEXTUREFILTER               1044
#define IDC_RECELLS                     1044
#define IDC_RESIZE                      1045
#define IDC_FRAMECOLORCTRL              1045
#define IDC_STATIC_CELLS                1046
#define IDC_STATIC_WIDTH                1047
#define IDC_LOCKTERRAIN                 1048
#define IDC_TABCENTER                   1050
#define IDC_TABBUTTON                   1052
#define IDC_TABBUTTON2                  1053
#define IDC_CELLSX                      1054
#define IDC_TABBUTTON3                  1054
#define IDC_CELLSY                      1055
#define IDC_TABBUTTON4                  1055
#define IDC_WIDTHX                      1057
#define IDC_WIDTHY                      1058
#define IDC_REWIDTHS                    1059
#define IDC_CURCELLSX                   1060
#define IDC_CURCELLSY                   1061
#define IDC_CURWIDTHX                   1062
#define IDC_CURWIDTHY                   1063
#define IDC_LOCK                        1064
#define IDC_ALIGNX                      1065
#define IDC_ALIGNY                      1066
#define IDC_CURCELLWIDTHX               1067
#define IDC_CURCELLWIDTHY               1068
#define IDC_CELLWIDTHX                  1069
#define IDC_CELLWIDTHY                  1070
#define IDC_RECELLWIDTHS                1071
#define IDC_ALPHAPALFRAME               1071
#define IDC_ZOOM                        1072
#define IDC_CURMAXHEIGHT                1072
#define IDC_SELCOLFRAME                 1073
#define IDC_SELTEXFRAME                 1074
#define IDC_MAXHEIGHT                   1074
#define IDC_ALPHAMAPFILENAME            1076
#define IDC_REHEIGHT                    1076
#define IDC_METASHADERNAME              1077
#define IDC_METASHADERFILENAME          1079
#define IDC_BUT_METASHADER              1080
#define IDC_BUT_ALPHAMAP                1081
#define IDC_DELETEINDEX                 1081
#define IDC_MS_CLOUDS                   1085
#define IDC_COMBO_TEXTOP                1086
#define IDC_PLAYERSTART                 1087
#define IDC_DRAWTEXTURE                 1088
#define IDC_ENABLEBREATH                1088
#define IDC_ENABLEDUST                  1089
#define IDC_LIGHTGRIDSIZE               1090
#define IDC_THINMESH                    1091
#define IDC_SAVE_MAP                    1092
#define IDC_SAVE_SHADER                 1093
#define IDC_DESCRIPTION                 1093
#define IDC_SAVE_PCX                    1094
#define IDC_FLIPA                       1094
#define IDC_FLIPB                       1095
#define IDC_MODELS                      1095
#define IDC_FLIPC                       1096
#define IDC_FLIPD                       1097
#define IDC_FLIPE                       1098
#define IDC_FLIPF                       1099
#define IDC_FLIPG                       1100
#define IDC_FLIPH                       1101
#define IDC_ENLARGE                     1102
#define IDC_POSTERIZE                   1103
#define IDC_LEVELS                      1104
#define IDC_INSERT                      1106
#define IDC_METASHADERFOLDER            1107
#define IDC_FRAMEAAS                    1108
#define IDC_MD3LIST                     1112
#define IDC_VIEWXZ                      1113
#define IDC_VIEWYZ                      1114
#define IDC_SLOPEANGLE                  1115
#define IDC_UNDOLEVELS                  1116
#define IDC_POSX                        1119
#define IDC_POSY                        1120
#define IDC_IMAGE                       1120
#define IDC_POSZ                        1121
#define IDC_BROWSE                      1122
#define IDC_HMAP_INFORMATION            1128
#define IDC_HMAP_HELP                   1129
#define IDC_IMPORT_MODELS               1131
#define IDC_IMPORT_WORLD                1132
#define IDC_LC_TERRAINS                 1134
#define IDC_BUTTON1                     1136
#define IDC_ORIGIN_SET                  1136
#define IDC_Q3MAP2OPTIONS               1136
#define IDC_REPLACEALL                  1136
#define IDC_ORIGIN_X                    1137
#define IDC_ORIGIN_Y                    1138
#define IDC_ORIGIN_Z                    1139
#define IDC_STEPLEFT                    1140
#define IDC_STEPRIGHT                   1141
#define IDC_STEPFORWARD                 1142
#define IDC_STEPBACKWARD                1143
#define IDC_STEPUP                      1144
#define IDC_STEPDOWN                    1145
#define IDC_STEPBY                      1146
#define IDC_ORIGIN_GET                  1147
#define IDC_EXPORTALLTRIS               1148
#define IDC_SLPAINT                     1149
#define IDC_PAINTRADIUS                 1150
#define IDC_SHADERSIGNORE               1151
#define IDC_WORLDWARNING                1152
#define IDC_MAP_INFO                    1153
#define IDC_VERTEXDRAGSTEP              1159
#define IDC_VERTEXDRAGSTEPSPIN          1161
#define IDC_SHADERTEMPLATE              1163
#define IDC_EDITTEMPLATE                1164
#define IDC_ETNOBLEND                   1165
#define IDC_TEXT                        1165
#define IDC_ETBLEND                     1166
#define IDC_ETVERTEX                    1167
#define IDC_MP_FIND                     1167
#define IDC_MP_REPWITH                  1168
#define ID_FILE_EXPORT_Q3AMAP           32771
#define ID_FILE_EXPORT_TXT              32772
#define ID_MODIFIER_APPLY               32775
#define ID_MODIFIER_HIDE                32776
#define ID_MODIFIER_NONE                32777
#define ID_CYCLE_RENDER_MODE            32778
#define ID_CYCLE_COLORS                 32779
#define ID_TEST                         32780
#define ID_TEX_FACTOR_UP                32785
#define ID_TEX_FACTOR_DN                32786
#define ID_TEX_FACTOR_NATURAL           32787
#define ID_TOGGLE_PLAYER_MOVE           32788
#define ID_TOGGLE_LIGHT                 32789
#define ID_FILE_EXPORT_BITMAP           32790
#define ID_FILE_IMPORT_BITMAP           32791
#define ID_TEXTURES_LOADDIR             32792
#define ID_TEXTURES_CLEAR               32793
#define ID_VIEW_WIRES                   32799
#define ID_VIEW_FLAT                    32801
#define ID_VIEW_TEXTURE                 32802
#define ID_VIEW_FLATSHADE               32804
#define ID_VIEW_FLATSMOOTH              32805
#define ID_VIEW_CULLING                 32807
#define ID_SELECTION_ROTATEZ            32809
#define ID_PREFERENCES                  -32726
#define ID_SHOWAXIS                     32812
#define ID_TOGGLEAXIS                   32813
#define ID_SELECTION_FLIP               32814
#define ID_SELECTION_MIRROR             32815
#define ID_SELECTION_ALL                32816
#define ID_TOGGLE_INEYE                 32820
#define ID_VIEW_ALPHAMAP                32822
#define ID_VIEW_ADDWIRES                32823
#define ID_FILE_EXPORT_ALPHAMAP         32825
#define ID_FILE_IMPORT_ALPHAMAP         32826
#define ID_FILE_EXPORT_METASHADER       32827
#define ID_VIEW_TRISFRAME               32829
#define ID_VIEW_NOFRAME                 32830
#define ID_FIXEDCAMERA                  32838
#define ID_EYECAMERA                    32839
#define ID_FLIP                         32840
#define ID_CAMERA_ALIGN                 32845
#define ID_CAMERA_LEFT                  32846
#define ID_CAMERA_RIGHT                 32847
#define ID_CAMERA_FORWARD               32848
#define ID_CAMERA_BACKWARD              32849
#define ID_CAMERA_STRAFELEFT            32850
#define ID_CAMERA_STRAFERIGHT           32851
#define ID_CAMERA_UP                    32852
#define ID_CAMERA_DOWN                  32853
#define ID_CAMERA_LOOKUP                32854
#define ID_CAMERA_LOOKDOWN              32855
#define ID_CAMERA_FLOOR                 32856
#define ID_CAMERA_ZEROH                 32857
#define ID_CAMERA_ALIGNZ                32858
#define ID_TOGGLE_FLATTRIS              32860
#define ID_BACKSPACE                    32862
#define ID_TOGGLE_SLOPE                 32865
#define ID_FILE_IMPORT_FROMMAP          32866
#define ID_TOGGLE_EXCLUDEDTRIS          32867
#define ID_TERRAIN_CLEAREXCLUDEDTRIS    32868
#define ID_WORLD_REMOVE                 32869
#define ID_WORLD_SHOW                   32870
#define ID_WORLD_HIDE                   32871
#define ID_TOGGLE_WORLD                 32872
#define ID_INDICATOR_MODIFIER           59100
#define ID_INDICATOR_PLAYER             59101
#define ID_INDICATOR_GRID               59102

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32875
#define _APS_NEXT_CONTROL_VALUE         1169
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
